name: institute_attendance_system
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1
  google_fonts: ^6.2.1

  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  fpdart: ^1.1.1
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
