name: institute_attendance_system
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.5
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod_lint: ^2.6.5
  go_router: ^16.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true
